# https://taskfile.dev

version: '3'

tasks:
    build:
      - conan create . --build=missing -s build_type=Release
    build-debug:
      - conan create . --build=missing -s build_type=Debug
    setup:
      - conan install . --build=missing -s build_type=Release
    setup-debug:
      - conan install . --build=missing -s build_type=Debug
